# Dockerfile.dev (dev com hot-reload)
FROM node:22-alpine

WORKDIR /usr/src/app

# Instala todas as deps no container
COPY package*.json ./
RUN npm ci

# Copia o resto
COPY . .

ENV NODE_ENV=development

EXPOSE 3000

# nodemon para autoreload
CMD ["npm", "run", "dev"]
